name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Install cargo-deny
      run: cargo install cargo-deny

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Lint with Clippy
      run: cargo clippy --workspace --all-features --bins --tests

    - name: cargo deny
      run: cargo deny --workspace check sources licenses advisories

    - name: Build
      run: cargo build --release --workspace --all-features --verbose

    - name: Run tests
      run: cargo test --all-features --workspace --verbose

    - name: Run docs
      run: cargo doc --workspace --all-features --no-deps --document-private-items --verbose
